//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr_avt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int IDAction { get; set; }
        public string NameAction { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime Completion_Date { get; set; }
        public int IDProduct { get; set; }
        public int Discount { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
