//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr_avt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int IDProduct { get; set; }
        public string NameProduct { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
    }
}
