//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr_avt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Ordering = new HashSet<Ordering>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime StopDate { get; set; }
        public string ProductName { get; set; }
        public int Discount { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Ordering> Ordering { get; set; }
        public virtual Product Product { get; set; }
    }
}
