//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr_avt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ordering = new HashSet<Ordering>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string PassportData { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Ordering> Ordering { get; set; }
        public virtual Role Role { get; set; }
    }
}
